spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/bootex
    username: bootuser
    password: bootuser

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      show_sql: true

  thymeleaf:
    cache: false
